# This workflow runs the tennis court booking script when triggered by an external event.

name: Tennis Court Booker

on:
  # This allows the workflow to be triggered by an external webhook call.
  repository_dispatch:
    types: [book-courts-event]

  # This is kept so you can still run the workflow manually from the Actions tab for testing.
  workflow_dispatch:

jobs:
  book-courts:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: playwright install --with-deps

    - name: Run booking script
      # The script will get its credentials and payment details from repository secrets.
      env:
        # Authentication credentials (matching your current setup)
        BRUCE_CAM_EMAIL_ADDRESS: ${{ vars.BRUCE_CAM_EMAIL_ADDRESS }}
        BRUCE_CAM_PASSWORD: ${{ secrets.BRUCE_CAM_PASSWORD }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        
        # Email recipients (all stored as variables in your repo)
        KYLE_EMAIL_ADDRESS: ${{ vars.KYLE_EMAIL_ADDRESS }}
        IT_EMAIL_ADDRESS: ${{ vars.IT_EMAIL_ADDRESS }}
        INFO_EMAIL_ADDRESS: ${{ vars.INFO_EMAIL_ADDRESS }}
        HELLO_EMAIL_ADDRESS: ${{ vars.HELLO_EMAIL_ADDRESS }}
        FATHER_CAM_EMAIL_ADDRESS: ${{ vars.FATHER_CAM_EMAIL_ADDRESS }}
        MOTHER_CAM_EMAIL_ADDRESS: ${{ vars.MOTHER_CAM_EMAIL_ADDRESS }}
        
        # Card payment details (will be added as secrets)
        LB_CARD_NUMBER: ${{ secrets.LB_CARD_NUMBER }}
        LB_CARD_EXPIRY_MONTH: ${{ secrets.LB_CARD_EXPIRY_MONTH }}
        LB_CARD_EXPIRY_YEAR: ${{ secrets.LB_CARD_EXPIRY_YEAR }}
        LB_CARD_SECURITY_CODE: ${{ secrets.LB_CARD_SECURITY_CODE }}
        
        # Cardholder details (will be added as secrets)
        LB_CARDHOLDER_NAME: ${{ secrets.LB_CARDHOLDER_NAME }}
        LB_ADDRESS: ${{ secrets.LB_ADDRESS }}
        LB_CITY: ${{ secrets.LB_CITY }}
        LB_POSTCODE: ${{ secrets.LB_POSTCODE }}
        
        # Production mode settings
        PRODUCTION_MODE: "true"
      run: python main.py

    - name: Upload Screenshots Artifact
      # This step now runs always, so any generated screenshots will be saved.
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: booking-screenshots
        path: screenshots/
        # This option prevents the workflow from failing if no screenshots were created.

        if-no-files-found: ignore


