# This workflow runs the tennis court booking script on a schedule.

name: Ca LIF Tennis Court Booker

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    # Books 5 weeks +-1 day ahead. Runs at 00:01 UTC on Tuesday (test), Wednesday, Friday, and Sunday.
    # Use https://crontab.guru/ to generate your desired schedule.
    - cron: '1 0 * * 2,3,5,0'

jobs:
  book-courts:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: playwright install --with-deps

    - name: Run booking script
      # Pass the secrets as environment variables to the Python script
      env:
        CAMDEN_USERNAME: ${{ secrets.CAMDEN_USERNAME }}
        CAMDEN_PASSWORD: ${{ secrets.CAMDEN_PASSWORD }}
      run: python main.py
